worldcoin/mini-apps-ui-kit

packages/mini-apps-ui-kit-react/stories/Input.stories.tsx
packages/mini-apps-ui-kit-react/stories/SearchField.stories.tsx

This pull request enhances the Storybook controls for the Input and SearchField components. It adds new control options for the Input component, including the ability to set the input's value and handle value changes. For the SearchField component, it adds new control options such as the ability to set an end adornment, display the input in an error or valid state, show a paste button, and set attributes like type, autocomplete, and spellcheck. These enhancements improve the customization and testing capabilities of the components in Storybook.

Enhance Storybook controls for Input and SearchField components

---

packages/mini-apps-ui-kit-react/src/tailwind/index.ts
packages/mini-apps-ui-kit-react/stories/documentation/Colors.mdx
packages/mini-apps-ui-kit-react/stories/documentation/components/Color.tsx
packages/mini-apps-ui-kit-react/tailwind.config.ts

This pull request adds color documentation to the project using Storybook MDX and color components. It introduces new color variables for gray, success, error, warning, and info. The color documentation is organized into sections for each color category, with each color displayed along with its name and code. This enhancement improves the project's documentation and provides a visual reference for the available colors.

Add color documentation with Storybook MDX and color components

---

examples/nextjs/app/page.tsx
packages/mini-apps-ui-kit-react/CHANGELOG.md
packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/Typography/Typography.tsx

Fixes type definition in the Typography component.

Improve Typography component type definitions and props

---

packages/mini-apps-ui-kit-react/.storybook/preview.css
packages/mini-apps-ui-kit-react/README.md
packages/mini-apps-ui-kit-react/stories/documentation/Icons.mdx

- Add Storybook documentation on iconography
- Update README with section on iconography

Add iconography documentation

---

packages/mini-apps-ui-kit-react/.storybook/preview.css
packages/mini-apps-ui-kit-react/README.md
packages/mini-apps-ui-kit-react/stories/documentation/Icons.mdx

Add Iconography pages

---

packages/mini-apps-ui-kit-react/src/components/Switch/Switch.tsx

Modify the height of the Switch component to improve its visual alignment.

Adjust Switch component height for better alignment

---

packages/mini-apps-ui-kit-react/src/components/RadioGroup/RadioGroupItem.tsx
packages/mini-apps-ui-kit-react/stories/RadioGroup.stories.tsx

Improve visual consistency and accessibility of the RadioGroupItem component. Add detailed documentation for the RadioGroup component in Storybook.

Refactor RadioGroupItem styles and enhance documentation

---

packages/mini-apps-ui-kit-react/src/components/Checkbox/Checkbox.tsx
packages/mini-apps-ui-kit-react/src/components/Icons/Tick.tsx
packages/mini-apps-ui-kit-react/stories/Checkbox.stories.tsx

Introduce additional props for better customization of the Checkbox component and improve the styling of the Tick icon for visual consistency. Update documentation for clarity.

Enhance Checkbox component with new props and improved styling

---

packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/Input/Input.tsx
packages/mini-apps-ui-kit-react/src/components/TextArea/TextArea.tsx
packages/mini-apps-ui-kit-react/src/components/TextArea/index.ts
packages/mini-apps-ui-kit-react/src/index.ts
packages/mini-apps-ui-kit-react/stories/TextArea.stories.tsx

Introduce a new TextArea component for multi-line text input, enhance the Input component styles, and add Storybook stories to demonstrate various states of the TextArea.

Add TextArea component to UI kit

---

packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/Progress/Progress.tsx
packages/mini-apps-ui-kit-react/src/components/Progress/index.ts
packages/mini-apps-ui-kit-react/src/components/Toast/use-toast.tsx
packages/mini-apps-ui-kit-react/src/index.ts
packages/mini-apps-ui-kit-react/stories/Progress.stories.tsx
pnpm-lock.yaml

Introduce a new Progress component for visualizing task completion, update dependencies, and include documentation in Storybook. Refactor unused imports in the toast component.

Add Progress component to UI kit

---

packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/AlertDialog/AlertDialog.tsx
packages/mini-apps-ui-kit-react/src/components/AlertDialog/index.ts
packages/mini-apps-ui-kit-react/src/components/AlertDialog/types.ts
packages/mini-apps-ui-kit-react/src/components/AlertDialog/use-alert-dialog.tsx
packages/mini-apps-ui-kit-react/src/components/BottomBar/BottomBar.tsx
packages/mini-apps-ui-kit-react/src/components/BottomBar/index.ts
packages/mini-apps-ui-kit-react/src/components/Drawer/Drawer.tsx
packages/mini-apps-ui-kit-react/src/components/Drawer/types.ts
packages/mini-apps-ui-kit-react/src/components/Drawer/use-drawer.ts
packages/mini-apps-ui-kit-react/src/components/Icons/XMark.tsx
packages/mini-apps-ui-kit-react/src/index.ts
packages/mini-apps-ui-kit-react/stories/AlertDialog.stories.tsx
packages/mini-apps-ui-kit-react/stories/BottomBar.stories.tsx
packages/mini-apps-ui-kit-react/stories/Drawer.stories.tsx
packages/mini-apps-ui-kit-react/stories/helpers/icons/CircleSpark.tsx
pnpm-lock.yaml

- Add AlertDialog.
- Update Drawer
- Add BottomBar (Fixes STU-1100)

Update Drawer, AlertDialog, BottomBar

---

packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/TopBar/TopBar.tsx
packages/mini-apps-ui-kit-react/src/components/TopBar/index.ts
packages/mini-apps-ui-kit-react/src/index.ts
packages/mini-apps-ui-kit-react/stories/TopBar.stories.tsx

Introduce a new TopBar component with customizable title and adornments, simplify its props, and enhance layout logic. Update Storybook documentation to showcase adornment options.

Add TopBar component

---

packages/mini-apps-ui-kit-react/src/components/ListItem/ListItem.tsx
packages/mini-apps-ui-kit-react/stories/ListItem.stories.tsx

Update the ListItem component to use a button element for better accessibility, add new props for label, description, and adornments, and improve styles and Storybook examples.

Refactor ListItem component for accessibility and enhanced props

---

packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/Tabs/Tabs.tsx
packages/mini-apps-ui-kit-react/src/components/Tabs/index.ts
packages/mini-apps-ui-kit-react/src/components/Tabs/types.ts
packages/mini-apps-ui-kit-react/src/tailwind/index.ts
packages/mini-apps-ui-kit-react/stories/Tabs.stories.tsx
packages/mini-apps-ui-kit-react/stories/helpers/icons/Apps.tsx
packages/mini-apps-ui-kit-react/stories/helpers/icons/Contacts.tsx
packages/mini-apps-ui-kit-react/stories/helpers/icons/Wallet.tsx
packages/mini-apps-ui-kit-react/stories/helpers/icons/WorldID.tsx

Introduce a Tabs component and TabItem for navigation, enhancing them with active icon functionality and improved layout. Update the tailwind configuration and add documentation in Storybook.

Add Tabs component with active icon support to mini-apps UI kit

---

packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/Button/Button.tsx
packages/mini-apps-ui-kit-react/src/components/Checkbox/Checkbox.tsx
packages/mini-apps-ui-kit-react/src/components/ClearButton/ClearButton.tsx
packages/mini-apps-ui-kit-react/src/components/ColorPicker/ColorPicker.tsx
packages/mini-apps-ui-kit-react/src/components/LiveFeedback/LiveFeedback.tsx
packages/mini-apps-ui-kit-react/src/components/NumberPad/NumberPad.tsx
packages/mini-apps-ui-kit-react/src/components/OTPField/OTPField.tsx
packages/mini-apps-ui-kit-react/src/components/PasswordField/PasswordField.tsx
packages/mini-apps-ui-kit-react/src/components/PasteButton/PasteButton.tsx
packages/mini-apps-ui-kit-react/src/components/PhoneField/GroupedCountryList.tsx
packages/mini-apps-ui-kit-react/src/components/RadioGroup/RadioGroup.tsx
packages/mini-apps-ui-kit-react/src/components/Select/Select.tsx
packages/mini-apps-ui-kit-react/src/components/Switch/Switch.tsx
packages/mini-apps-ui-kit-react/src/components/Tabs/Tabs.tsx
packages/mini-apps-ui-kit-react/src/components/Toast/use-toast.tsx
packages/mini-apps-ui-kit-react/src/components/ToggleGroup/ToggleGroup.tsx
packages/mini-apps-ui-kit-react/src/lib/haptics.ts

- Added haptic feedback functionality to various components including Checkbox, ColorPicker, RadioGroup, and Switch using the new withHaptics utility.
- Implemented haptic notifications for success and error states in LiveFeedback and Toast components.
- Introduced a new haptics utility module to manage different types of haptic feedback.
- Enhanced user interaction by providing tactile responses for button clicks and state changes.
Fixes STU-1241

Add haptic feedback

---

.changeset/kind-toys-kick.md
packages/mini-apps-ui-kit-react/CHANGELOG.md
packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/tailwind/index.ts

Introduce new color utilities in Tailwind configuration.

Fix Tailwind color utilities

---

packages/mini-apps-ui-kit-react/package.json

bump version to 1.0.2

---

examples/nextjs/app/layout.tsx
examples/nextjs/app/page.tsx
packages/mini-apps-ui-kit-react/.storybook/main.ts
packages/mini-apps-ui-kit-react/CHANGELOG.md
packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/Haptic/Haptic.tsx
packages/mini-apps-ui-kit-react/src/components/Haptic/index.ts
packages/mini-apps-ui-kit-react/src/components/Haptic/use-haptics.ts
packages/mini-apps-ui-kit-react/src/index.ts
packages/mini-apps-ui-kit-react/src/lib/haptics.ts
packages/mini-apps-ui-kit-react/stories/Haptic.stories.tsx
packages/mini-apps-ui-kit-react/stories/documentation/Haptics.mdx
pnpm-lock.yaml

- Introduced the Haptic component to provide haptic feedback on user interactions, supporting types such as impact, notification, and selection changes.
- Created a useHaptics hook for easier integration of haptic feedback across components.
- Updated haptics utility to include new types for better type safety.
- Added Storybook stories for the Haptic component to demonstrate its functionality and usage.

feat: Add Haptic component for tactile feedback

---

packages/mini-apps-ui-kit-react/CHANGELOG.md
packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/Toast/Toast.tsx
packages/mini-apps-ui-kit-react/src/components/Toast/Toaster.tsx

Propagate events from the ToastViewport to elements below.

Propagate click events from ToastViewport to elements below.

---

packages/mini-apps-ui-kit-react/CHANGELOG.md
packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/components/SearchField/SearchField.tsx

- Show/hide clear button based in the content of the input.

Hide clear button when no content in PhoneField

---

packages/mini-apps-ui-kit-react/stories/Toast.stories.tsx

- Updated the Toast component's documentation to provide comprehensive details on features, usage examples, and API reference.
- Included sections on basic and advanced usage, manual toast control, and best practices for displaying toasts.
- Improved accessibility information and added haptic feedback details for mobile users.

Update Toast docs

---

README.md
packages/mini-apps-ui-kit-react/CHANGELOG.md
packages/mini-apps-ui-kit-react/package.json
packages/mini-apps-ui-kit-react/src/index.ts

- `PasswordField` component is exposed from the package
- `README.md` was slightly tweaked

Export `PasswordField` component from the package
